#!/bin/bash

# 检查并启用 ARM64 架构支持
echo "启用 ARM64 架构支持..."

# 获取 Ubuntu 版本号
UBUNTU_VERSION=$(lsb_release -c | awk '{print $2}')

# 更新 /etc/apt/sources.list 文件，添加 ubuntu-ports 软件源
echo "更新 /etc/apt/sources.list 文件..."
sudo bash -c "cat <<EOF >> /etc/apt/sources.list

# ubuntu-ports 软件源 for arm64
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $UBUNTU_VERSION main restricted universe multiverse
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $UBUNTU_VERSION-updates main restricted universe multiverse
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $UBUNTU_VERSION-security main restricted universe multiverse
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $UBUNTU_VERSION-backports main restricted universe multiverse
EOF"

# 更新软件源
echo "更新软件源..."
sudo dpkg --add-architecture arm64
sudo apt update


# 安装 ARM64 软件包示例（如 qemu-user-static）
# echo "安装 ARM64 软件包 qemu-user-static:arm64..."
# sudo apt install -y qemu-user-static:arm64 qemu-utils:arm64 qemu-system-common:arm64

echo "脚本执行完成！"
