name: Debian-RootFS-DistroBox x86-64 Pull and Save Docker Image
on:
  # push:
  #   branches:
  #     - main
  workflow_run:
    workflows:
      - Build-Debian-RootFS-DistroBox-AMD64
    types:
      - completed
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'jamesmith0817/debian-rootfs-distrobox'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean Up Environments
      run: | 
        # sudo apt-get update && sudo apt-get install -y wget curl
        # wget https://raw.githubusercontent.com/actions/runner-images/refs/heads/main/images/ubuntu/toolsets/toolset-2004.json
        # APT_PACKAGES=`cat toolset-2004.json | jq -r '.apt | [.vital_packages[], .common_packages[], .cmd_packages[]] | del(.[] | select(. == "lib32z1")) | join(" ")'`
        # sudo apt update && sudo apt-get purge -y ${APT_PACKAGES} && df -h
        sudo bash ./envcleaner.sh      

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        # # images="jamesmith0817/debian-rootfs-distrobox"
        # IFS=',' read -r -a image_array <<< "$images"
        # for image in "${image_array[@]}"; do
          docker pull jamesmith0817/debian-rootfs-distrobox --platform "linux/amd64"
          docker save jamesmith0817/debian-rootfs-distrobox -o "debian-rootfs-distrobox-amd64.tar"
        # done

    - name: Compress the TAR files
      run: tar -czf x86-64-images.tar.gz *-amd64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: x86-64-images.tar.gz
        retention-days: 90  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar